server:
  port: 8081

spring:
  mvc:
    servlet:
      path: /api/v1

  main:
    allow-bean-definition-overriding: false

  output:
    ansi:
      enabled: ALWAYS

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      # Каналы для Pub/Sub механизма Redis
      channels:
        post-view-event: "app:post:viewed"
        comment-event: "app:comment:created"
        like-event: "app:post:liked"
        user-banner-event: "app:user:banned"


    kafka:
      bootstrap-servers: localhost:9092
      groupId: post_service #TODO: Пока непонятно нужен он или нет

      producer:
        acks: all #TODO: Подтверждение и повторная попытка  # Гарантия получения
        retries: 10 #TODO: Производители Kafka должны указать уровень подтверждения, известный как acks # Кол-во повторов при ошибке
        retry.backoff.ms: 1000 #TODO: надо разобраться надо или нет  # Интервал между попытками

      # Темы Kafka с количеством партиций и фактором репликации
      topics:
        topic_post: post_topic
        partitions_post: 10
        replication_post: 3

        topic_post_view: post_view
        partitions_post_view: 10
        replication_post_view: 3

        topic_like: like
        partitions_like: 10
        replication_like: 3

        topic_comment: comment
        partitions_comment: 10
        replication_comment: 3

        topic_feed_heat: feed_heat
        partitions_feed_heat: 5 #TODO: Пока непонятно сколько вообще нужно ставить, надо в конце последней таски смотреть
        replication_feed_heat: 3

  task:
    execution:
      pool:
        core-size: 5
        max-size: 20
        queue-capacity: 100
        threadNamePrefix: "PostAnalytics-"

logging: #TODO: Непонятно зачем нужно
  level:
    root: info

# Feign-клиенты
user-service:
  host: localhost
  port: 8080

project-service:
  host: localhost
  port: 8082

payment-service:
  host: localhost
  port: 9080

# Плановые задачи
scheduled:
  author-banner: "@daily"

# Лимиты
limits:
  post:
    unverified_post_limit: 5
  like:
    user-fetch:
      batch-size: 100