name: Compile and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  compile_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: gradle

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@c59fdc5a3c87acbe418fabae54cc8710145cfa92

      - name: Build with Gradle
        run: ./gradlew compileJava

      - name: Run tests
        run: ./gradlew test